default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  database: Steam_rb_development
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

test:
  <<: *default
  database: Steam_rb_test
  
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
